#include <string>
#include <iostream>
using namespace std;

string Grass[] = {
"222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222"
  };

string Bird[] = {
    "6600  ",
    "666644",
    "      "
  };

string unBird[] = {
    "333333",
    "333333",
    "333333"
  };

string Tubo1[30] = {
    "  AA  AA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    " 22222222 ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    " 22222222 ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "          "
  };

string Tubo2[30] = {
    "  AAAAAA  ",
    "  AA  AA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    " 22222222 ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    " 22222222 ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "          "};
string Tubo3[30] = {
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AA  AA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    " 22222222 ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    " 22222222 ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "          "};
string Tubo4[30] = {
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AA  AA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    " 22222222 ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    " 22222222 ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "          "};
string Tubo5[30] = {
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AA  AA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    " 22222222 ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    " 22222222 ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "          "};
string Tubo6[30] = {
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AA  AA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    " 22222222 ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    " 22222222 ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "          "};
string Tubo7[30] = {
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AA  AA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    " 22222222 ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    " 22222222 ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "          "};
string Tubo8[30] = {
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AA  AA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    " 22222222 ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    "          ",
    " 22222222 ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "  AAAAAA  ",
    "          "};

string unPipe[] = {
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    " 33333333 ",
    "          "
  };
  
